version: "3.6"
services:
  dk_app_nginx:
    container_name: ct_app_nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html # acesso do servidor
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf # configurações do servidor
    depends_on:
      - dk_app_php
  dk_app_php:
    container_name: ct_app_php
    build: .
    image: php-fpm_composer:dev
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./html:/var/www/html # acesso para execuçao
      - ./conf/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini # configurações de execução
    environment:
      XDEBUG_MODE: debug # ,profile,coverage ,develop,trace,gcstats
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    depends_on:
      - dk_app_mysql
  dk_app_node:
    image: node:latest
    container_name: ct_app_node
    restart: unless-stopped
    ports:
      - "5173:5173"
    tty: true
    volumes:
      - ./html:/var/www/html
    working_dir: /var/www/html
    command: npm run dev
    depends_on:
      - dk_app_nginx
  dk_app_mysql:
    image: mysql:5.7
    container_name: ct_app_mysql
    restart: always
    environment:
      MYSQL_DATABASE: baseinfo
      MYSQL_USER: user_app
      MYSQL_PASSWORD: passinfo
      MYSQL_ROOT_PASSWORD: passinfo
    # volumes:
    #   - ./docker_compose/mysql/data/:/var/lib/mysql # dados db
    #   - ./docker_compose/mysql:/docker-entrypoint-initdb.d # migrate inicial
    ports:
      - "3306:3306"
